version: '3.3'
services:
  db:
    container_name: database
    image: postgres
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ../datadb:/var/lib/postgresql/data
    env_file: .env
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}
    networks:
      - develop-networks

  web:
    container_name: mynginx
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    volumes:
      - ../templates:/etc/nginx/templates
    ports:
      - "80:80"
    restart: always
    env_file: .env
    environment:
      NGINX_HOST: "vcnafacul.com"
      NGINX_PORT: 80
    networks:
      - develop-networks
    depends_on:
      - db

networks:
  develop-networks:
    driver: bridge
