version: '3.9'
services: 
    db:
        image: postgres
        container_name: database
        environment: 
            POSTGRES_PASSWORD: postgres
        ports: 
            - 5432:5432
        volumes:
            - ../datadb:/var/lib/postgresql/data
            - ./docker:/home
