version: '3.3'
services: 
  db:
    build: 
      dockerfile: ./docker/postgres.dockerfile
      context: .
    image: postgres
    container_name: database
    ports: 
      - ${PG_PORT}:5432
    volumes:
      - ../datadb:/var/lib/postgresql/data
    env_file: .env
    restart: always
    environment: 
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
    networks: 
      - develop-networks

  app:
    image: node:14
    container_name: mynode
    working_dir: /var/www/
    env_file: .env
    restart: always
    ports: 
      - ${PORT}:3333
    networks: 
      - develop-networks
    volumes: 
      - ./build:/var/www/
    entrypoint: ["yarn"]
    command: ['migration']
    command: ['production']
    depends_on: 
      - db
  web:
    build: 
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: nginx:1.10.1-alpine
    volumes:
      - ../templates:/etc/nginx/templates
    container_name: mynginx
    ports: 
      - "80:80"
    restart: always
    environment: 
      NGINX_HOST: "vcnafacul.com"
      NGINX_PORT: 80
    networks: 
      - develop-networks
    depends_on: 
      - app

networks:
  develop-networks:
    driver: bridge