import '../app/Features/Auth/routes'
import '../app/Features/BancoQuestoes/routes'
import '../app/Features/Simulados/routes'
import '../app/Features/Geolocations/routes'
import '../app/Features/PrepSchools/routes'
